#访问地址，端口
server:
  servlet:
    context-path: /SW
  port: 8060
  #配置tomcat
  tomcat:
    max-threads: 300
    max-connections: 20000
#连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/normal_nover?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis  jdbc:mysql://localhost:3306/normal_nover?serverTimezone=Asia/Shanghai zeroDateTimeBehavior=CONVERT_TO_NULL


mvc:
  static-path-pattern: /**
  resources:
    static-locations: classpath:/static



mybatis:
  mapper-locations:   classpath:mapping/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
#开发环境swagger开启
swagger:
  enabled: true

#jwt相关信息
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: DG  #JWT负载中拿到开头


#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  row-bounds-with-count: false
  reasonable: true

#用户默认密码
user:
  pwd : "123456"

management:
  security:
    enabled : false

#全局变量
sqlfactory:
  sql_system: "http://47.94.154.152:8073/"

logging:
  level:
    cn.SoulMen.business: debug #打印sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
